- hosts: localhost
  connection: local
  vars:
    dmg_path: "{{ansible_env.HOME}}/Downloads"
    dmgs:
      - {
        name: "Franz",
        url: "https://github.com/meetfranz/franz/releases/download/v5.0.0-beta.14/franz-5.0.0-beta.14.dmg",
        force: false,
        installed_name: "no_path",
        state: "present"
      }
  pre_tasks:
  - name: Install .dmgs
    get_url:
      url: "{{ item.url }}"
      dest: "{{ dmg_path }}/{{ item.name }}.dmg"
    with_items: "{{ dmgs }}"
  roles:
    - role: pipersniper.macos_installer

  tasks:
  - name: homebrew | update
    command: brew update
  - name: homebrew | outdated
    command: brew outdated
    register: homebrew
  - debug: var=homebrew.stdout_lines
  - name: brewcask | outdated
    command: brew cask outdated
    register: brewcask
  - debug: var=brewcask.stdout_lines
  - name: mas | outdated
    command: mas outdated
    register: macas
  - debug: var=macas.stdout_lines
  - name: homebrew | upgrade
    command: brew upgrade
  - name: brewfile | install
    command: brew bundle
    register: brewfile
  - debug: var=brewfile.stdout_lines
