#!/bin/sh

if [ -f $HOME/.package.json ]; then
  mv $HOME/.package.json $HOME/package.json
  echo "Installation of package.json"
fi

if [ -f $HOME/.composer.json ]; then
  mv $HOME/.composer.json $HOME/composer.json
  echo "Installation of package.json"
fi
